### ISSUE TITLE
Feature request: configuration-based discovery

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#86]
As an alternative to zyre discovery a short-term fix (and long term, for stable cluster configurations) configuration based discovery might be worthwhile.

**Comment by hintjens** [comment]
Yes. Right now Zyre is using zbeacon to discover peers. However this is IMO
not working properly on your boxes.

It's going to be quite heavy for configuration management if every cluster
node has to specify every other cluster node. Can we find some shortcut,
e.g. is there a single interface on all boxes we can use for UDP discovery
and cluster interconnects?

**Comment by hintjens** [comment]
So there is an option in zbeacon to force it to use a specific interface by setting the ZSYS_INTERFACE environment variable to the interface name or IP address. We can also set that programatically from the zbroker config file, however it'd worth testing via ZSYS_INTERFACE first.

**Comment by rpedde** [comment]
Will test and advise

**Comment by rpedde** [comment]
With regard to the heavy configuration management, etc.  In almost every application I've ever used, the ability of the code to cope with strange configurations is always overwhelmed by the ability to make (or be forced to use) configurations which flummox auto-config.  While automatic configuration can be good enough in a large majority of cases, in my experience there are _always_ cases that disabling auto-config is worthwhile and necessary.

Doubly so with networking configs.

One issue I've already run into is that broadcast is _very_ problematic on openflow networks, and broadcasts are disabled on cloud provider non-sdn interfaces, making broadcast discovery difficult to test on cloud instances (which makes gating and integration testing hard).

Another issue is discovery across collision domains (which is a theoretical problem at this point, but shortly won't be).  Another issue is discovery against saturated cabinet uplinks -- tcp copes, broadcast discovery doesn't.

In general, I feel that explicit is better than implicit (albeit more difficult to configure), and large scale distributed configuration management is a well understood and solved problem.

I think autoconfiguration is worthwhile, but an opt-out would make sense in some configurations, or so I believe.

**Comment by hintjens** [comment]
Do we still need this feature?

We can use the zyre/port setting to isolate clusters on their own virtual network.

**Comment by hintjens** [comment]
So there are several options here. What I'd like to explore is a mix of configuration and gossip, so that you can boot a Zyre cluster with sparse explicit discovery statements. Basically this is a generalization of a discovery server approach where every Zyre node can act as server.

How this would work:
- We switch off beacon-based discovery, as a config option.
- The Zyre node gets one or more peers to connect to, as configured statements.
- When it successfully connects to a peer, the two peers tell each other about other peers they know about.
- Peers continue to connect and explore and broadcast new peers they have discovered.
- For efficiency we can (perhaps) record the discovered peers at each node so start-up is faster.

In practice this means you'd only have to add a single line to a config file for any given peer, in order to connect it to the whole cluster.

**Comment by rpedde** [comment]
This allows well known discovery nodes on different sides of collision domains, too, so I like this.  This allows switching between either of the methods of discovery, or intermingled.  

I like this approach.

**Comment by hintjens** [comment]
OK, I'll start on a minimal version and we can take it from there.

**Comment by hintjens** [comment]
I've finished a first cut: https://github.com/zeromq/czmq/pull/507

This was not as easy as I'd thought. It took a few abortive attempts. However I think the design is simple now, totally separate from Zyre and usable as a plugin discovery service.
